In [ ]:
import pandas as pd
df = pd.read_parquet('nyc.parquet')

In [ ]:
df.head(8)

In [3]:
df.shape

(20940373, 25)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20940373 entries, 0 to 20940372
Data columns (total 25 columns):
 #   Column                Dtype
---  ------                -----
 0   hvfhs_license_num     object
 1   dispatching_base_num  object
 2   originating_base_num  object
 3   request_datetime      datetime64[us]
 4   on_scene_datetime     datetime64[us]
 5   pickup_datetime       datetime64[us]
 6   dropoff_datetime      datetime64[us]
 7   PULocationID          int32
 8   DOLocationID          int32
 9   trip_miles            float64
 10  trip_time             int64
 11  base_passenger_fare   float64
 12  tolls                 float64
 13  bcf                   float64
 14  sales_tax             float64
 15  congestion_surcharge  float64
 16  airport_fee           float64
 17  tips                  float64
 18  driver_pay            float64
 19  shared_request_flag   object
 20  shared_match_flag     object
 21  access_a_ride_flag    object
 22  wav_request_flag      object
 23  wav_match_flag        object
 24  cbd_congestion_fee    float64
dtypes: datetime64[us](4), float64(10), int32(2), int64(1), object(8)
memory usage: 3.7+ GB

In [5]:
df.isnull().sum().sum()

np.int64(5676843)

In [ ]:
## Sampling the data to make it suitable for model analysis and training
import pandas as pd

df = pd.read_parquet('nyc.parquet')

sample = df.sample(100000, random_state=42)

sample.to_csv("sample.csv", index=False)

In [3]:
import pandas as pd
#######sample verfiy
sample = pd.read_parquet('../data/sampled/sample_1.parquet')
sample.shape

(100000, 15)

In [8]:
##combine sample datafram
combine_df=pd.read_csv('../data/sampled/combined_sample.csv')
combine_df.head()

,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tolls,congestion_surcharge,airport_fee,tips,driver_pay,trip_minutes,trip_speed,pickup_hour,pickup_dayofweek,is_weekend
0,231,125,0.60,255,13.59,0.0,2.75,0.0,0.0,6.48,4.250000,0.140845,16,3,0
1,236,260,5.49,1247,44.25,0.0,2.75,0.0,0.0,29.59,20.783333,0.264027,0,3,0
2,214,221,4.42,1493,21.01,0.0,0.00,0.0,0.0,23.89,24.883333,0.177558,7,3,0
3,144,233,3.09,692,17.66,0.0,2.75,0.0,0.0,11.46,11.533333,0.267687,23,5,1
4,61,189,2.34,769,16.91,0.0,0.00,0.0,0.0,11.77,12.816667,0.182432,20,5,1

In [9]:
combine_df.shape

(1000000, 15)

In [10]:
#duplicates
combine_df[combine_df.duplicated()]

Empty DataFrame
Columns: [PULocationID, DOLocationID, trip_miles, trip_time, base_passenger_fare, tolls, congestion_surcharge, airport_fee, tips, driver_pay, trip_minutes, trip_speed, pickup_hour, pickup_dayofweek, is_weekend]
Index: []

In [1]:
import pandas as pd,numpy as np
import warnings
warnings.filterwarnings('ignore')
combine_df = pd.read_parquet('../data/sampled/combined_sample.parquet')
print("null check")
print(combine_df.isnull().sum())
print("duplicate check")
print(combine_df[combine_df.duplicated()])
print("data types")
print(combine_df.dtypes)
print("target statistics")

## this section will remove any edges cases in the target 

combine_df= combine_df[combine_df['base_passenger_fare'] > 0]
combine_df = combine_df[combine_df['trip_miles'] > 0]
combine_df = combine_df[combine_df['trip_time'] > 0]

# Remove extreme outliers (optional but recommended)
fare_upper = combine_df['base_passenger_fare'].quantile(0.99)
combine_df = combine_df[combine_df['base_passenger_fare'] <= fare_upper]

print(f"Rows after cleanup: {combine_df.shape[0]}")

null check
PULocationID            0
DOLocationID            0
trip_miles              0
trip_time               0
base_passenger_fare     0
tolls                   0
congestion_surcharge    0
airport_fee             0
tips                    0
driver_pay              0
trip_minutes            0
trip_speed              0
pickup_hour             0
pickup_dayofweek        0
is_weekend              0
dtype: int64
duplicate check
Empty DataFrame
Columns: [PULocationID, DOLocationID, trip_miles, trip_time, base_passenger_fare, tolls, congestion_surcharge, airport_fee, tips, driver_pay, trip_minutes, trip_speed, pickup_hour, pickup_dayofweek, is_weekend]
Index: []
data types
PULocationID              int32
DOLocationID              int32
trip_miles              float64
trip_time                 int64
base_passenger_fare     float64
tolls                   float64
congestion_surcharge    float64
airport_fee             float64
tips                    float64
driver_pay              float64
trip_minutes            float64
trip_speed              float64
pickup_hour               int32
pickup_dayofweek          int32
is_weekend                int64
dtype: object
target statistics
Rows after cleanup: 985238

In [ ]:
print(combine_df['base_passenger_fare'].describe())

count    985238.000000
mean         24.350035
std          18.759229
min           0.070000
25%          11.650000
50%          18.340000
75%          30.190000
max         121.180000
Name: base_passenger_fare, dtype: float64

In [2]:
print("Columns in dataset:")
print(combine_df.columns.tolist())

Columns in dataset:
['PULocationID', 'DOLocationID', 'trip_miles', 'trip_time', 'base_passenger_fare', 'tolls', 'congestion_surcharge', 'airport_fee', 'tips', 'driver_pay', 'trip_minutes', 'trip_speed', 'pickup_hour', 'pickup_dayofweek', 'is_weekend']