In [3]:
import pandas as pd

In [ ]:
input_file = "../data/raw/splits/nyc_part_1.parquet"

In [5]:

df=pd.read_parquet(input_file)
df.shape

(2097152, 25)

In [7]:
df.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag,cbd_congestion_fee
0,HV0003,B03404,B03404,2026-01-01 00:50:37,2026-01-01 00:52:31,2026-01-01 00:54:30,2026-01-01 01:13:23,262,79,4.300,...,2.75,0.0,0.00,21.10,N,N,N,N,N,1.5
1,HV0003,B03404,B03404,2026-01-01 00:09:12,2026-01-01 00:12:17,2026-01-01 00:12:39,2026-01-01 00:22:42,195,52,1.890,...,0.00,0.0,0.00,9.10,N,N,N,N,N,0.0
2,HV0003,B03404,B03404,2026-01-01 00:16:16,2026-01-01 00:29:33,2026-01-01 00:31:34,2026-01-01 00:55:21,25,181,1.840,...,0.00,0.0,2.67,21.94,N,N,N,N,N,0.0
3,HV0005,B03406,None,2026-01-01 00:08:19,2026-01-01 00:09:08,2026-01-01 00:09:37,2026-01-01 00:22:12,141,226,3.307,...,2.75,0.0,0.00,13.42,N,N,N,N,Y,1.5
4,HV0005,B03406,None,2026-01-01 00:21:16,2026-01-01 00:26:30,2026-01-01 00:26:40,2026-01-01 00:39:06,226,226,2.060,...,0.00,0.0,2.98,11.39,N,N,N,N,Y,0.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2097152 entries, 0 to 2097151
Data columns (total 25 columns):
 #   Column                Dtype
---  ------                -----
 0   hvfhs_license_num     object
 1   dispatching_base_num  object
 2   originating_base_num  object
 3   request_datetime      datetime64[us]
 4   on_scene_datetime     datetime64[us]
 5   pickup_datetime       datetime64[us]
 6   dropoff_datetime      datetime64[us]
 7   PULocationID          int32
 8   DOLocationID          int32
 9   trip_miles            float64
 10  trip_time             int64
 11  base_passenger_fare   float64
 12  tolls                 float64
 13  bcf                   float64
 14  sales_tax             float64
 15  congestion_surcharge  float64
 16  airport_fee           float64
 17  tips                  float64
 18  driver_pay            float64
 19  shared_request_flag   object
 20  shared_match_flag     object
 21  access_a_ride_flag    object
 22  wav_request_flag      object
 23  wav_match_flag        object
 24  cbd_congestion_fee    float64
dtypes: datetime64[us](4), float64(10), int32(2), int64(1), object(8)
memory usage: 384.0+ MB

In [6]:

## Check for duplicates
df.duplicated().sum()

np.int64(0)

In [22]:

df[df.duplicated()]

Empty DataFrame
Columns: [PULocationID, DOLocationID, trip_miles, trip_time, base_passenger_fare, tolls, congestion_surcharge, airport_fee, tips, driver_pay, trip_minutes, trip_speed, pickup_hour, pickup_dayofweek, is_weekend]
Index: []

In [11]:
df.isnull().sum().sum()

np.int64(576270)

In [21]:
df.isnull().any()

PULocationID            False
DOLocationID            False
trip_miles              False
trip_time               False
base_passenger_fare     False
tolls                   False
congestion_surcharge    False
airport_fee             False
tips                    False
driver_pay              False
trip_minutes            False
trip_speed              False
pickup_hour             False
pickup_dayofweek        False
is_weekend              False
dtype: bool

In [8]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [9]:
df.isnull().sum()

request_datetime        0
on_scene_datetime       0
pickup_datetime         0
dropoff_datetime        0
PULocationID            0
DOLocationID            0
trip_miles              0
trip_time               0
base_passenger_fare     0
tolls                   0
congestion_surcharge    0
airport_fee             0
tips                    0
driver_pay              0
dtype: int64

In [11]:
df.head()

,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tolls,congestion_surcharge,airport_fee,tips,driver_pay
0,2026-01-01 00:50:37,2026-01-01 00:52:31,2026-01-01 00:54:30,2026-01-01 01:13:23,262,79,4.300,1133,31.24,0.0,2.75,0.0,0.00,21.10
1,2026-01-01 00:09:12,2026-01-01 00:12:17,2026-01-01 00:12:39,2026-01-01 00:22:42,195,52,1.890,604,8.95,0.0,0.00,0.0,0.00,9.10
2,2026-01-01 00:16:16,2026-01-01 00:29:33,2026-01-01 00:31:34,2026-01-01 00:55:21,25,181,1.840,1427,24.06,0.0,0.00,0.0,2.67,21.94
3,2026-01-01 00:08:19,2026-01-01 00:09:08,2026-01-01 00:09:37,2026-01-01 00:22:12,141,226,3.307,755,24.91,0.0,2.75,0.0,0.00,13.42
4,2026-01-01 00:21:16,2026-01-01 00:26:30,2026-01-01 00:26:40,2026-01-01 00:39:06,226,226,2.060,746,17.86,0.0,0.00,0.0,2.98,11.39

In [15]:
df.to_parquet("../data/processed/clean_split_1.parquet", index=False)

In [23]:
##cleaning 2
input_file = "../data/raw/splits/nyc_part_2.parquet"
df=pd.read_parquet(input_file)

In [25]:
df.isnull().sum().sum()

np.int64(543543)

In [26]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [27]:
df.shape

(2097152, 14)

In [28]:
df.to_parquet("../data/processed/clean_split_2.parquet", index=False)

In [30]:
##cleaning 3
input_file = "../data/raw/splits/nyc_part_3.parquet"
df=pd.read_parquet(input_file)

In [31]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [32]:
df.to_parquet("../data/processed/clean_split_3.parquet", index=False)

In [33]:
input_file = "../data/raw/splits/nyc_part_4.parquet"
df=pd.read_parquet(input_file)

In [34]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [36]:
df.shape

(2097152, 14)

In [35]:
df.to_parquet("../data/processed/clean_split_4.parquet", index=False)

In [37]:
##5!!
input_file = "../data/raw/splits/nyc_part_5.parquet"
df=pd.read_parquet(input_file)

In [38]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [39]:
df.to_parquet("../data/processed/clean_split_5.parquet", index=False)

In [40]:
##6!!
input_file = "../data/raw/splits/nyc_part_6.parquet"
df=pd.read_parquet(input_file)

In [41]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [42]:
df.to_parquet("../data/processed/clean_split_6.parquet", index=False)

In [43]:
#7!!
input_file = "../data/raw/splits/nyc_part_7.parquet"
df=pd.read_parquet(input_file)

In [44]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [45]:
df.to_parquet("../data/processed/clean_split_7.parquet", index=False)

In [46]:
#8!!
input_file = "../data/raw/splits/nyc_part_8.parquet"
df=pd.read_parquet(input_file)

In [47]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [48]:
df.to_parquet("../data/processed/clean_split_8.parquet", index=False)

In [49]:
#9!!
input_file = "../data/raw/splits/nyc_part_9.parquet"
df=pd.read_parquet(input_file)

In [50]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [55]:
df.shape

(2066005, 14)

In [51]:
df.to_parquet("../data/processed/clean_split_9.parquet", index=False)

In [52]:
#10!!
input_file = "../data/raw/splits/nyc_part_10.parquet"
df=pd.read_parquet(input_file)

In [53]:
columns_to_drop = [
    "originating_base_num",
    "hvfhs_license_num",
    "dispatching_base_num",
    "sales_tax",
    "bcf",
    "cbd_congestion_fee",
    "shared_request_flag",
    "shared_match_flag",
    "access_a_ride_flag",
    "wav_request_flag",
    "wav_match_flag"
]

df = df.drop(columns=columns_to_drop)

In [54]:
df.to_parquet("../data/processed/clean_split_10.parquet", index=False)